# Generated by Django 4.0.6 on 2022-07-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0004_pessoa_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='cargo',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cargo',
            field=models.ManyToManyField(to='autenticacao.cargos'),
        ),
    ]
